version: '3'

services:

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com -d www.example.com
  

  webserver:
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    container_name: webserver
    restart: unless-stopped
    ports:
        - "8080:80"
        #- "443:443"

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   ports:
  #   - 8080:8080

  # db:
  #   image: postgres:13
  #   container_name: postgres
  #   restart: always
  #   volumes:
  #     - db:/var/lib/postgresql/
  #   environment:
  #     - MYSQL_PASSWORD=
  #     - POSTGRES_DB=nextcloud
  #     - POSTGRES_USER=nextcloud

  
  

# volumes:
#   certbot-etc:
#   dbdata:

# networks:
#   app-network:
#     driver: bridge