version: '3'

volumes:
  nextcloud:
  db:

services:

  webserver:
        build: .
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8080:80"
            #- "443:443"

