version: '3'

volumes:
  nextcloud:
  db:

services:

  webserver:
        image: nginx:1.21.1-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "80:80"
            #- "443:443"
        volumes:
            #- wordpress:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
            - ./website:/usr/share/nginx/html/
            #- certbot-etc:/etc/letsencrypt
volumes:
  website:
